### ISSUE TITLE
Issues Running Test Sample Project with Revit 2025

### ISSUE THREAD

**Issue by GreenHeinz** [ricaun-io/RevitTest#3]
Hello,

I'm encountering difficulties getting the Test Sample Project to function with Revit 2025, despite adjusting the RevitVersion to 2025 and the TargetFramework to net8.0-windows. Revit 2024 operates smoothly with net48. In your video titled "Update unit test to run Revit 2025 - Revit API," I observed that you managed to initiate the test with Revit 2025, indicating its feasibility.

To address the initial error, I installed Microsoft.NET.Test.SDK. However, subsequent to this action, I encountered another error stating that no tests were discoverable.

Do you have any suggestions for resolving this issue?

Thank you.

# RevitTest.Samples
```
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>Latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <Configurations>Debug;Release</Configurations>
    <RevitVersion>2025</RevitVersion>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

```

# Without Test.SDk
```
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 406
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 223
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 149
========== Test discovery aborted: 0 Tests found in 8,7 ms ==========
```

# With Test.SDK
```
========== Starting test discovery ==========
TestAdapter: ricaun.RevitTest.TestAdapter 	1.3.1 	[Net Core]
Application: ricaun.RevitTest.Console.zip
DiscoverTests: Tests not found [C:\Users\xxx\Documents\Repos\RevitTest\RevitTest.Samples\bin\Debug\net8.0-windows\RevitTest.Samples.dll]
No test is available in C:\Users\xxx\Documents\Repos\RevitTest\RevitTest.Samples\bin\Debug\net8.0-windows\RevitTest.Samples.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 5,9 sec ==========
```

**Comment by ricaun** [comment]
Yes! In NET Code, you need to add the package `Microsoft.NET.Test.Sdk`.

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
```

I gonna create a new video and update this project to support version 2025 on the fly.

**Comment by ricaun** [comment]
Try to build the project before, running the tests. In .NET Core something changes in the name discovery and every time you build the project you lose the test reference in the Test Explorer.

You could add the log to level 2 in the project to show some info.
```c#
[assembly: System.Reflection.AssemblyMetadata("NUnit.Verbosity", "2")]
```
To see if the discovery is finding the tests.

**Comment by ricaun** [comment]
I updated the main sample to have the versions Revit 2024 and Revit 2025. #4

**Comment by GreenHeinz** [comment]
I tried again with the changes you made, but I still get the "Test not found" error. I tried the repository on a different PC, and there I don't have any problems. This suggests that there may be some strange security network settings in our work environment because this error occurs on different work PCs but not on my private PC. So, this problem seems to be with the Microsoft.Test.SDK and has nothing to do with your framework.
Do you have any ideas? If not, no worries, our IT team is already on the case! ;)

```
// The "Failed to load assembly" happens on my work and private PC, dont know if this is normal?
TpTrace Information: 0 : 14012, 8, 2024/04/19, 08:24:23.328, 1627398122112, testhost.dll, Application: ricaun.RevitTest.Console.zip
TpTrace Verbose: 0 : 14012, 8, 2024/04/19, 08:24:23.328, 1627398122809, testhost.dll, TestRequestHandler.SendData: sending data from testhost: {"Version":7,"MessageType":"TestSession.Message","Payload":{"MessageLevel":0,"Message":"Application: ricaun.RevitTest.Console.zip"}}
TpTrace Verbose: 0 : 14012, 8, 2024/04/19, 08:24:23.328, 1627398124228, testhost.dll, MulticastDelegateUtilities.SafeInvoke: TestRunMessageLoggerProxy.SendMessage: Invoking callback 1/1 for Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscoveryManager., took 0 ms.
TpTrace Information: 0 : 14012, 8, 2024/04/19, 08:24:23.589, 1627400731253, testhost.dll, AssemblyResolver.OnResolve: ricaun.Security.WinTrust.1.0.1: Resolving assembly.
TpTrace Information: 0 : 14012, 8, 2024/04/19, 08:24:23.589, 1627400732378, testhost.dll, AssemblyResolver.OnResolve: ricaun.Security.WinTrust.1.0.1: Searching in: 'C:\Users\xxx\Documents\Repos\RevitTest\RevitTest.Samples\bin\Debug\net8.0-windows'.
TpTrace Information: 0 : 14012, 8, 2024/04/19, 08:24:23.589, 1627400733063, testhost.dll, AssemblyResolver.OnResolve: ricaun.Security.WinTrust.1.0.1: Assembly path does not exist: 'C:\Users\xxx\Documents\Repos\RevitTest\RevitTest.Samples\bin\Debug\net8.0-windows\ricaun.Security.WinTrust.1.0.1.dll', returning.
TpTrace Information: 0 : 14012, 8, 2024/04/19, 08:24:23.589, 1627400733633, testhost.dll, AssemblyResolver.OnResolve: ricaun.Security.WinTrust.1.0.1: Assembly path does not exist: 'C:\Users\xxx\Documents\Repos\RevitTest\RevitTest.Samples\bin\Debug\net8.0-windows\ricaun.Security.WinTrust.1.0.1.exe', returning.
TpTrace Information: 0 : 14012, 8, 2024/04/19, 08:24:23.589, 1627400733925, testhost.dll, AssemblyResolver.OnResolve: ricaun.Security.WinTrust.1.0.1: Failed to load assembly.
// Log Errors, which doesn't happen on my private PC:
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:23.767, 1627402516397, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1000 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:24.780, 1627412640910, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1012 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:25.794, 1627422783436, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1013 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:26.809, 1627432932941, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1014 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:27.823, 1627443070630, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1013 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:28.835, 1627453199178, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1012 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:29.850, 1627463347010, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1014 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:30.864, 1627473484324, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1013 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:31.865, 1627483494451, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1000 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:32.878, 1627493624875, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1012 ms
TpTrace Verbose: 0 : 14012, 10, 2024/04/19, 08:24:33.893, 1627503771861, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:56702 localEndPoint: [::ffff:127.0.0.1]:56705 after 1014 ms
TpTrace Information: 0 : 14012, 4, 2024/04/19, 08:24:34.605, 1627510892243, testhost.dll, TestDiscoveryManager.RunMessage: calling TestRunMessage(Warning, DiscoverTests: Tests not found [C:\Users\xxx\Documents\Repos\RevitTest\RevitTest.Samples\bin\Debug\net8.0-windows\RevitTest.Samples.dll]) callback.
TpTrace Warning: 0 : 14012, 4, 2024/04/19, 08:24:34.605, 1627510894297, testhost.dll, DiscoverTests: Tests not foud
```

**Comment by ricaun** [comment]
Never seen this issue before... Just to confirm, when running with NET. Framework the test runs fine, right?

It looks like the PC is blocking something, the adapter uses the temporary folder to copy the `ricaun.RevitTest.Console.zip`  and package `ricaun.Security.WinTrust` both embedded inside the TestAdapter.

At least on my PC after the `OnResolve Failed to load assembly.` I have this log with the location in the temp folder.
```
TpTrace Information: 0 : 13616, 7, 2024/04/23, 11:12:29.296, 933101571852, testhost.dll, AssemblyResolver.OnResolve: ricaun.Security.WinTrust.1.0.1: Failed to load assembly.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\xxx\AppData\Local\Temp\Costura\52970C76188329E4FEF419CD4B5CD068\ricaun.security.wintrust.1.0.1.dll'. Module was built without symbols.
```

I didn't know the `testhost.dll` uses tcp local connection, and if the problem is in the `Microsoft.NET.Test.Sdk` package, did you test using the default NUnit TestAdapter config for net8.0?.

Some config like:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
  </ItemGroup>
```

If the problem is in the `Microsoft.NET.Test.Sdk` and some security blocking TCP maybe, `NUnit3TestAdapter` would fail.

**Comment by ricaun** [comment]
Hello @GreenHeinz 

Looks like the issue was fixed, I updated the main sample to have the `Microsoft.NET.Test.Sdk` package when using NET Core.

Like this:
```
<ItemGroup>
  <PackageReference Include="NUnit" Version="3.13.3" />
  <PackageReference Include="ricaun.RevitTest.TestAdapter" Version="*" />
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" Condition="!$(TargetFramework.StartsWith('net4'))" />
</ItemGroup>
```
